AWSTemplateFormatVersion: 2010-09-09
Description: Braze Components Application

Mappings:
    Constants:
        Stack:
            Value: targeting
        App:
            Value: braze-components

Parameters:
    Stage:
        Type: String
    WebrootBucket:
        Type: String
    DomainName:
        Type: String
    TLSCert:
        Type: String
        Description: ARN of TLS certificate in US-EAST-1
    WebrootAccessIdentityID:
        Type: String
        Description: ID of CloudFront origin access identity for webroot bucket access (check output of static-s3 stack)

Resources:
    CDN:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                Aliases:
                    - !Ref DomainName
                Origins:
                    - Id: !Sub braze-components-${Stage}
                      DomainName: !Sub ${WebrootBucket}.s3.amazonaws.com
                      OriginPath: !Sub /${Stage}/braze-components-storybook-static
                      S3OriginConfig:
                          OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${WebrootAccessIdentityID}
                DefaultCacheBehavior:
                    AllowedMethods: [HEAD, GET]
                    CachedMethods: [HEAD, GET]
                    MinTTL: 60
                    MaxTTL: 60
                    Compress: true
                    ForwardedValues:
                        QueryString: false
                    TargetOriginId: !Sub braze-components-${Stage}
                    ViewerProtocolPolicy: redirect-to-https
                DefaultRootObject: index.html
                CustomErrorResponses:
                    - ErrorCachingMinTTL: 5
                      ErrorCode: 404
                PriceClass: PriceClass_100
                Enabled: true
                ViewerCertificate:
                    AcmCertificateArn: !Ref TLSCert
                    MinimumProtocolVersion: TLSv1
                    SslSupportMethod: sni-only
                HttpVersion: http2
            Tags:
                - Key: app
                  Value: !FindInMap [Constants, App, Value]
                - Key: stack
                  Value: !FindInMap [Constants, Stack, Value]
                - Key: stage
                  Value: !Ref Stage
