name: Chromatic
on: push

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2.4.0

            - name: Use Node.js
              uses: guardian/actions-setup-node@main

            - name: Install dependencies
              run: |
                  yarn install

            - name: Chromatic
              uses: chromaui/action@v1
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  token: ${{ secrets.GITHUB_TOKEN }}
