name: Chromatic
on: push

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0

            - run: npm install --global corepack@0.31.0
              shell: bash
            - run: corepack enable
              shell: bash

            - name: Use Node.js
              uses: actions/setup-node@v6
              with:
                  node-version-file: '.nvmrc'

            - name: Install dependencies
              run: |
                  pnpm install

            - name: Chromatic
              uses: chromaui/action@v17
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  token: ${{ secrets.GITHUB_TOKEN }}
