name: lint
on: push

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3.0.1

            - name: Use Node.js
              uses: guardian/actions-setup-node@main

            - name: Install dependencies
              run: yarn install

            - name: Lint
              run: yarn lint
